name: CI/CD Pipeline

on:
  push:
    branches:
      - Aziz-Ben-Ismail-Universite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # ou la version de Java requise pour votre projet

      - name: Build and Test
        run: |
          mvn clean
          mvn compile
          mvn test

      - name: Deploy
        run: |
          mvn deploy
